//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkExperiment.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public System.DateTime effective_date { get; set; }
        public string plan_name { get; set; }
        public string plan_id { get; set; }
        public string formulary_id { get; set; }
        public Nullable<bool> active { get; set; }
        public string customer_id { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> quarterly_enrollment { get; set; }
        public Nullable<int> average_enrollment { get; set; }
        public Nullable<int> month1_enrollment { get; set; }
        public Nullable<int> month2_enrollment { get; set; }
        public Nullable<int> month3_enrollment { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string claims_processor { get; set; }
        public string mail_order_vendor { get; set; }
        public string formulary_type { get; set; }
        public Nullable<int> number_of_tiers { get; set; }
        public string plan_type { get; set; }
        public string copay_differentials { get; set; }
        public string formulary_name { get; set; }
        public string benefit_type { get; set; }
        public string benefit_plan { get; set; }
        public string benefit_design { get; set; }
        public string t2_vs_t3 { get; set; }
        public Nullable<bool> new_member_flag { get; set; }
        public string business_segment { get; set; }
        public string model_type_code { get; set; }
        public string cms_sponsor_id { get; set; }
        public string cms_formulary_id { get; set; }
        public string plan_website_url { get; set; }
        public Nullable<bool> medicaid_indicator_flag { get; set; }
        public string internal_business_unit_id { get; set; }
    
        public virtual Сustomer Customer { get; set; }
    }
}
